-- Tablas para checklist de mantenimiento
CREATE TABLE IF NOT EXISTS actividades_checklist (
    id_actividad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    orden INTEGER,
    estado BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS actividades_realizadas (
    id_actividad_realizada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mantenimiento INTEGER NOT NULL,
    id_actividad INTEGER NOT NULL,
    realizada BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_actividad_mantenimiento FOREIGN KEY (id_mantenimiento)
        REFERENCES mantenimientos (id_mantenimiento),
    CONSTRAINT fk_actividad_checklist FOREIGN KEY (id_actividad)
        REFERENCES actividades_checklist (id_actividad)
);

-- Precarga de actividades (10)
INSERT INTO actividades_checklist (nombre, categoria, orden, estado) VALUES
('Limpieza de polvo interior', 'LIMPIEZA_FISICA', 1, TRUE),
('Limpieza de teclado y pantalla', 'LIMPIEZA_FISICA', 2, TRUE),
('Revisión de ventiladores y disipadores', 'LIMPIEZA_FISICA', 3, TRUE),
('Actualización de sistema operativo', 'SOFTWARE', 1, TRUE),
('Actualización de drivers', 'SOFTWARE', 2, TRUE),
('Escaneo de antivirus', 'SOFTWARE', 3, TRUE),
('Revisión de programas instalados', 'SOFTWARE', 4, TRUE),
('Prueba de batería o fuente de poder', 'HARDWARE', 1, TRUE),
('Revisión de puertos USB y conexiones', 'HARDWARE', 2, TRUE),
('Prueba de memoria RAM y disco', 'HARDWARE', 3, TRUE)
ON CONFLICT DO NOTHING;
