# ═══════════════════════════════════════════
# Perfil DEV — consumogestionactivosapi
# ═══════════════════════════════════════════
# Activar con: spring.profiles.active=dev

spring.thymeleaf.cache=false

logging.level.com.uisrael.consumogestionactivosapi=DEBUG
