# ═══════════════════════════════════════════
# Perfil PROD — consumogestionactivosapi
# ═══════════════════════════════════════════
# Activar con: spring.profiles.active=prod

spring.thymeleaf.cache=true

logging.level.com.uisrael.consumogestionactivosapi=WARN

server.error.include-stacktrace=never
server.error.include-message=never
