# ═══════════════════════════════════════════
# Perfil DEV — consumogestionactivosapi
# ═══════════════════════════════════════════
# Activar con: spring.profiles.active=dev

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

logging.level.com.uisrael.consumogestionactivosapi=DEBUG

# Mail en dev (necesario para que JavaMailSender se autoconfigure)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=
spring.mail.password=
