

api.connect-timeout=3
api.read-timeout=15

spring.thymeleaf.cache=true

logging.level.com.uisrael.consumogestionactivosapi=WARN

server.error.include-stacktrace=never
server.error.include-message=never
