ALTER TABLE ubicaciones
    ALTER COLUMN latitud TYPE NUMERIC(10,7) USING NULLIF(BTRIM(latitud::TEXT), '')::NUMERIC(10,7),
    ALTER COLUMN longitud TYPE NUMERIC(10,7) USING NULLIF(BTRIM(longitud::TEXT), '')::NUMERIC(10,7);
