-- V1: Esquema base CRESIO
-- Crea todas las tablas que el sistema legacy tenía en V1-V17.
-- Completamente idempotente: usa CREATE TABLE IF NOT EXISTS en todo.
-- Las migraciones V18+ agregan columnas, renombran o eliminan — operan sobre este base.

-- =============================================
-- TABLAS INDEPENDIENTES (sin FK externas)
-- =============================================

CREATE TABLE IF NOT EXISTS roles (
    id_rol      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50)  NOT NULL,
    estado      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    tipo            VARCHAR(20)  NOT NULL DEFAULT 'ADMINISTRATIVO',
    estado          BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS marcas (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(100) NOT NULL,
    estado   BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS categorias_equipo (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(50)  NOT NULL,
    estado       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS modulos (
    id_modulo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    VARCHAR(50)  NOT NULL,
    nombre    VARCHAR(100) NOT NULL,
    icono     VARCHAR(50),
    ruta      VARCHAR(255),
    orden     INTEGER,
    estado    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_modulos_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS empresas (
    id_empresa  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(200) NOT NULL,
    ruc         VARCHAR(13)  NOT NULL,
    direccion   VARCHAR(500),
    telefono    VARCHAR(20),
    correo      VARCHAR(150),
    estado      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    deleted_at  TIMESTAMP(6),
    CONSTRAINT uk_empresas_ruc UNIQUE (ruc)
);

-- =============================================
-- TABLAS CON DEPENDENCIAS SIMPLES
-- =============================================

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    cedula          VARCHAR(20),
    correo          VARCHAR(150) NOT NULL,
    contrasena      VARCHAR(255) NOT NULL,
    estado          BOOLEAN      NOT NULL DEFAULT TRUE,
    fcm_token       VARCHAR(512),
    id_departamento INTEGER,
    id_rol          INTEGER,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    deleted_at      TIMESTAMP(6),
    CONSTRAINT uk_usuarios_correo  UNIQUE (correo),
    CONSTRAINT uk_usuarios_cedula  UNIQUE (cedula),
    CONSTRAINT fk_usuarios_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos (id_departamento),
    CONSTRAINT fk_usuarios_rol          FOREIGN KEY (id_rol)          REFERENCES roles (id_rol)
);

CREATE TABLE IF NOT EXISTS roles_modulos (
    id_rol_modulo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol        INTEGER NOT NULL,
    id_modulo     INTEGER NOT NULL,
    CONSTRAINT fk_roles_modulos_rol    FOREIGN KEY (id_rol)    REFERENCES roles   (id_rol),
    CONSTRAINT fk_roles_modulos_modulo FOREIGN KEY (id_modulo) REFERENCES modulos (id_modulo)
);

CREATE TABLE IF NOT EXISTS cargos (
    id_cargo        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    estado          BOOLEAN      NOT NULL DEFAULT TRUE,
    fk_departamento INTEGER,
    CONSTRAINT fk_cargos_departamento FOREIGN KEY (fk_departamento) REFERENCES departamentos (id_departamento)
);

-- ubicaciones: fk_departamento se añade en V19, aquí va sin esa FK
CREATE TABLE IF NOT EXISTS ubicaciones (
    id_ubicacion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    agencia         VARCHAR(100) NOT NULL DEFAULT '',
    estado          BOOLEAN      NOT NULL DEFAULT TRUE,
    latitud         NUMERIC(10,7),
    longitud        NUMERIC(10,7),
    direccion       VARCHAR(255),
    ciudad          VARCHAR(100),
    parroquia       VARCHAR(150),
    provincia       VARCHAR(100),
    link_coordenada VARCHAR(500),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    deleted_at      TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS custodios (
    id_custodio  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    cedula       VARCHAR(20)  NOT NULL,
    correo       VARCHAR(150),
    telefono     VARCHAR(20),
    fecha_ingreso DATE,
    estado       BOOLEAN      NOT NULL DEFAULT TRUE,
    fk_cargo     INTEGER,
    fk_ubicacion INTEGER,
    fk_usuario   INTEGER,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    deleted_at   TIMESTAMP(6),
    CONSTRAINT fk_custodios_cargo     FOREIGN KEY (fk_cargo)     REFERENCES cargos     (id_cargo),
    CONSTRAINT fk_custodios_ubicacion FOREIGN KEY (fk_ubicacion) REFERENCES ubicaciones (id_ubicacion),
    CONSTRAINT fk_custodios_usuario   FOREIGN KEY (fk_usuario)   REFERENCES usuarios   (id_usuario)
);

-- =============================================
-- EQUIPOS (tabla central)
-- =============================================

CREATE TABLE IF NOT EXISTS equipos (
    id_equipo                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_sap                 VARCHAR(20),
    modelo                     VARCHAR(100),
    serial                     VARCHAR(100),
    procesador                 VARCHAR(100),
    memoria_ram_gb             INTEGER,
    capacidad_almacenamiento_gb INTEGER,
    licencia_windows_activada  BOOLEAN,
    mac                        VARCHAR(100),
    fecha_compra               DATE,
    precio_compra              NUMERIC(10,2),
    estado_equipo              VARCHAR(50),
    observacion_equipo         TEXT,
    estado                     BOOLEAN NOT NULL DEFAULT TRUE,
    id_marca                   INTEGER NOT NULL,
    id_categoria               INTEGER NOT NULL,
    created_at                 TIMESTAMP(6),
    updated_at                 TIMESTAMP(6),
    created_by                 VARCHAR(100),
    updated_by                 VARCHAR(100),
    deleted_at                 TIMESTAMP(6),
    CONSTRAINT fk_equipos_marca     FOREIGN KEY (id_marca)     REFERENCES marcas           (id_marca),
    CONSTRAINT fk_equipos_categoria FOREIGN KEY (id_categoria) REFERENCES categorias_equipo (id_categoria)
);

-- =============================================
-- CUSTODIAS
-- =============================================

CREATE TABLE IF NOT EXISTS custodias (
    id_custodia_equipo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo          INTEGER NOT NULL,
    id_custodio        INTEGER NOT NULL,
    fecha_inicio       DATE,
    fecha_fin          DATE,
    observacion        TEXT,
    estado             BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_movimiento    VARCHAR(50),
    ruta_acta_pdf      VARCHAR(500),
    ruta_acta_firmada  VARCHAR(500),
    fk_ubicacion       INTEGER,
    CONSTRAINT fk_custodias_equipo   FOREIGN KEY (id_equipo)   REFERENCES equipos   (id_equipo),
    CONSTRAINT fk_custodias_custodio FOREIGN KEY (id_custodio) REFERENCES custodios  (id_custodio)
);

-- =============================================
-- MANTENIMIENTOS
-- =============================================

CREATE TABLE IF NOT EXISTS mantenimientos (
    id_mantenimiento    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id           INTEGER,
    cliente_id          INTEGER,
    empresa_id          INTEGER,
    fecha_programada    TIMESTAMP NOT NULL,
    fec_cierre          TIMESTAMP,
    descripcion         VARCHAR(2000),
    tipo_mantenimiento  VARCHAR(30),
    id_usuario          INTEGER,
    estado              VARCHAR(30),
    creado_en           TIMESTAMP,
    estado_interno      VARCHAR(30),
    estado_general      VARCHAR(20),
    proxima_fecha       DATE,
    fk_programado       INTEGER,
    odoo_ticket_id      VARCHAR(50),
    tipo_origen         VARCHAR(30),
    activo              BOOLEAN,
    -- campos de snapshot del equipo
    serie_snapshot      VARCHAR(100),
    year_snapshoted     INTEGER,
    codigo_interno_snapshot VARCHAR(100),
    CONSTRAINT fk_mantenimientos_equipo  FOREIGN KEY (equipo_id)  REFERENCES equipos   (id_equipo),
    CONSTRAINT fk_mantenimientos_cliente FOREIGN KEY (cliente_id) REFERENCES custodios (id_custodio),
    CONSTRAINT fk_mantenimientos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas  (id_empresa)
);

-- =============================================
-- TABLAS LEGACY (serán eliminadas por V25, pero deben existir para que V18 sea idempotente)
-- =============================================

CREATE TABLE IF NOT EXISTS actualizacion_activos (
    id_actualizacion          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_usuario_actualizacion  INTEGER,
    descripcion               TEXT,
    fecha_actualizacion       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activos (
    id_activo           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion         TEXT,
    fecha_adquisicion   DATE,
    valor_actual        DOUBLE PRECISION
);

-- =============================================
-- MÓDULOS Y ROL-MÓDULOS
-- =============================================

CREATE TABLE IF NOT EXISTS rol_modulos (
    id_rol_modulo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id        INTEGER NOT NULL,
    modulo_id     INTEGER NOT NULL,
    CONSTRAINT uk_rol_modulos UNIQUE (rol_id, modulo_id),
    CONSTRAINT fk_rol_modulos_rol    FOREIGN KEY (rol_id)    REFERENCES roles   (id_rol),
    CONSTRAINT fk_rol_modulos_modulo FOREIGN KEY (modulo_id) REFERENCES modulos (id_modulo)
);

-- =============================================
-- MANTENIMIENTOS: tablas de soporte
-- =============================================

CREATE TABLE IF NOT EXISTS mantenimientos_programados (
    id_programado                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id                    INTEGER NOT NULL,
    tecnico_id                   INTEGER NOT NULL,
    frecuencia_dias              INTEGER NOT NULL,
    fecha_ultimo_mantenimiento   DATE,
    fecha_proximo_mantenimiento  DATE NOT NULL,
    estado                       BOOLEAN,
    observaciones                TEXT,
    CONSTRAINT fk_mant_prog_equipo  FOREIGN KEY (equipo_id)  REFERENCES equipos  (id_equipo),
    CONSTRAINT fk_mant_prog_tecnico FOREIGN KEY (tecnico_id) REFERENCES usuarios (id_usuario)
);

CREATE TABLE IF NOT EXISTS mantenimiento_equipos (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mantenimiento_id INTEGER NOT NULL,
    equipo_id        INTEGER NOT NULL,
    CONSTRAINT fk_mant_eq_mant  FOREIGN KEY (mantenimiento_id) REFERENCES mantenimientos (id_mantenimiento),
    CONSTRAINT fk_mant_eq_equipo FOREIGN KEY (equipo_id)       REFERENCES equipos        (id_equipo)
);

CREATE TABLE IF NOT EXISTS actividades_checklist (
    id_actividad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(200) NOT NULL,
    orden        INTEGER,
    estado       BOOLEAN
);

CREATE TABLE IF NOT EXISTS checklist_categoria (
    id_actividad INTEGER NOT NULL,
    id_categoria INTEGER NOT NULL,
    PRIMARY KEY (id_actividad, id_categoria),
    CONSTRAINT fk_ck_cat_actividad  FOREIGN KEY (id_actividad) REFERENCES actividades_checklist (id_actividad),
    CONSTRAINT fk_ck_cat_categoria  FOREIGN KEY (id_categoria) REFERENCES categorias_equipo     (id_categoria)
);

CREATE TABLE IF NOT EXISTS actividades_realizadas (
    id_actividad_realizada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mantenimiento       INTEGER NOT NULL,
    id_actividad           INTEGER NOT NULL,
    realizada              BOOLEAN,
    CONSTRAINT fk_act_real_mant FOREIGN KEY (id_mantenimiento) REFERENCES mantenimientos      (id_mantenimiento),
    CONSTRAINT fk_act_real_act  FOREIGN KEY (id_actividad)     REFERENCES actividades_checklist (id_actividad)
);

CREATE TABLE IF NOT EXISTS imagenes_mantenimiento (
    id_imagen        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mantenimiento INTEGER      NOT NULL,
    nombre_archivo   VARCHAR(255) NOT NULL,
    ruta_archivo     VARCHAR(500) NOT NULL,
    tamanio_bytes    BIGINT,
    CONSTRAINT fk_img_mant FOREIGN KEY (id_mantenimiento) REFERENCES mantenimientos (id_mantenimiento)
);

CREATE TABLE IF NOT EXISTS firmas_mantenimiento (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mantenimiento INTEGER NOT NULL,
    tipo_firma       VARCHAR(20) NOT NULL,
    firma_base64     TEXT        NOT NULL,
    firmado_en       TIMESTAMP   NOT NULL,
    ip_origen        VARCHAR(45),
    firmado_por_id   INTEGER,
    CONSTRAINT fk_firma_mant   FOREIGN KEY (id_mantenimiento) REFERENCES mantenimientos (id_mantenimiento),
    CONSTRAINT fk_firma_usuario FOREIGN KEY (firmado_por_id)  REFERENCES usuarios       (id_usuario)
);

-- =============================================
-- ACTIVIDADES PLANIFICADAS
-- =============================================

CREATE TABLE IF NOT EXISTS actividades_planificadas (
    id_actividad_planificada   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnico_id                 INTEGER      NOT NULL,
    creado_por_id              INTEGER      NOT NULL,
    titulo                     VARCHAR(200) NOT NULL,
    descripcion                TEXT,
    tipo_actividad             VARCHAR(50)  NOT NULL,
    prioridad                  VARCHAR(20)  NOT NULL,
    estado                     VARCHAR(30)  NOT NULL,
    fecha_inicio               DATE         NOT NULL,
    fecha_fin                  DATE         NOT NULL,
    fecha_completada           TIMESTAMP,
    tiempo_estimado_minutos    INTEGER,
    tiempo_real_minutos        INTEGER,
    referencia_mantenimiento_id INTEGER,
    observaciones              TEXT,
    fk_mantenimiento_prog      BIGINT,
    fk_equipo                  INTEGER,
    created_at                 TIMESTAMP(6),
    updated_at                 TIMESTAMP(6),
    created_by                 VARCHAR(100),
    updated_by                 VARCHAR(100),
    deleted_at                 TIMESTAMP(6),
    CONSTRAINT fk_act_plan_tecnico  FOREIGN KEY (tecnico_id)    REFERENCES usuarios              (id_usuario),
    CONSTRAINT fk_act_plan_creador  FOREIGN KEY (creado_por_id) REFERENCES usuarios              (id_usuario),
    CONSTRAINT fk_act_plan_mant     FOREIGN KEY (referencia_mantenimiento_id) REFERENCES mantenimientos (id_mantenimiento),
    CONSTRAINT fk_act_plan_prog     FOREIGN KEY (fk_mantenimiento_prog) REFERENCES mantenimientos_programados (id_programado),
    CONSTRAINT fk_act_plan_equipo   FOREIGN KEY (fk_equipo) REFERENCES equipos (id_equipo)
);

-- =============================================
-- NOTIFICACIONES, CONSENTIMIENTO, UBICACIÓN TÉCNICO
-- =============================================

CREATE TABLE IF NOT EXISTS notificaciones (
    id_notificacion              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id                   INTEGER      NOT NULL,
    mensaje                      VARCHAR(255) NOT NULL,
    url                          VARCHAR(500),
    leida                        BOOLEAN,
    creado_en                    TIMESTAMP,
    referencia_mantenimiento_id  INTEGER,
    referencia_actividad_id      BIGINT,
    CONSTRAINT fk_notif_usuario  FOREIGN KEY (usuario_id)                  REFERENCES usuarios              (id_usuario),
    CONSTRAINT fk_notif_mant     FOREIGN KEY (referencia_mantenimiento_id) REFERENCES mantenimientos        (id_mantenimiento),
    CONSTRAINT fk_notif_actividad FOREIGN KEY (referencia_actividad_id)    REFERENCES actividades_planificadas (id_actividad_planificada)
);

CREATE TABLE IF NOT EXISTS consentimiento_monitoreo (
    id_consentimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id        INTEGER     NOT NULL,
    fecha_aceptacion  TIMESTAMP   NOT NULL,
    version_terminos  VARCHAR(20) NOT NULL DEFAULT '1.0',
    ip_aceptacion     VARCHAR(45),
    activo            BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en         TIMESTAMP,
    CONSTRAINT fk_consent_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id_usuario)
);

CREATE TABLE IF NOT EXISTS ubicaciones_tecnicos (
    id_ubicacion_tecnico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id           INTEGER        NOT NULL,
    latitud              NUMERIC(10, 7) NOT NULL,
    longitud             NUMERIC(10, 7) NOT NULL,
    precision_metros     NUMERIC(6, 2),
    timestamp_captura    TIMESTAMP      NOT NULL,
    creado_en            TIMESTAMP,
    CONSTRAINT fk_ubic_tec_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id_usuario)
);
