ALTER TABLE equipos
    ADD COLUMN IF NOT EXISTS codigo_cresio VARCHAR(20),
    ADD COLUMN IF NOT EXISTS estado_inventario VARCHAR(50),
    ADD COLUMN IF NOT EXISTS id_bodega_actual INTEGER,
    ADD COLUMN IF NOT EXISTS id_orden_compra INTEGER,
    ADD COLUMN IF NOT EXISTS fecha_garantia DATE,
    ADD COLUMN IF NOT EXISTS etiquetado BOOLEAN;

CREATE UNIQUE INDEX IF NOT EXISTS ux_equipos_codigo_cresio
    ON equipos (codigo_cresio)
    WHERE codigo_cresio IS NOT NULL;

CREATE TABLE IF NOT EXISTS bodegas (
    id_bodega INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    ciudad VARCHAR(100),
    direccion VARCHAR(255),
    estado BOOLEAN,
    id_custodio_responsable INTEGER,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted_at TIMESTAMP(6),
    CONSTRAINT uk_bodegas_codigo UNIQUE (codigo),
    CONSTRAINT fk_bodegas_custodio_responsable
        FOREIGN KEY (id_custodio_responsable) REFERENCES custodios (id_custodio)
);

CREATE TABLE IF NOT EXISTS consumibles (
    id_consumible INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255),
    unidad_medida VARCHAR(30),
    estado BOOLEAN,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted_at TIMESTAMP(6),
    CONSTRAINT uk_consumibles_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS ordenes_compra (
    id_orden_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_oc VARCHAR(60) NOT NULL,
    proveedor VARCHAR(150),
    fecha_emision DATE,
    fecha_recepcion DATE,
    estado VARCHAR(30) NOT NULL,
    observacion TEXT,
    id_bodega_destino INTEGER,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted_at TIMESTAMP(6),
    CONSTRAINT uk_ordenes_compra_numero_oc UNIQUE (numero_oc),
    CONSTRAINT fk_ordenes_compra_bodega_destino
        FOREIGN KEY (id_bodega_destino) REFERENCES bodegas (id_bodega)
);

CREATE TABLE IF NOT EXISTS ordenes_compra_detalle (
    id_orden_compra_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden_compra INTEGER NOT NULL,
    tipo_item VARCHAR(20) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    cantidad_solicitada INTEGER NOT NULL,
    cantidad_recibida INTEGER,
    id_categoria INTEGER,
    id_marca INTEGER,
    id_consumible INTEGER,
    CONSTRAINT fk_oc_detalle_orden
        FOREIGN KEY (id_orden_compra) REFERENCES ordenes_compra (id_orden_compra),
    CONSTRAINT fk_oc_detalle_categoria
        FOREIGN KEY (id_categoria) REFERENCES categorias_equipo (id_categoria),
    CONSTRAINT fk_oc_detalle_marca
        FOREIGN KEY (id_marca) REFERENCES marcas (id_marca),
    CONSTRAINT fk_oc_detalle_consumible
        FOREIGN KEY (id_consumible) REFERENCES consumibles (id_consumible)
);

CREATE TABLE IF NOT EXISTS stock_consumible_bodega (
    id_stock_consumible_bodega INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bodega INTEGER NOT NULL,
    id_consumible INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    CONSTRAINT uk_stock_bodega_consumible UNIQUE (id_bodega, id_consumible),
    CONSTRAINT fk_stock_bodega
        FOREIGN KEY (id_bodega) REFERENCES bodegas (id_bodega),
    CONSTRAINT fk_stock_consumible
        FOREIGN KEY (id_consumible) REFERENCES consumibles (id_consumible)
);

CREATE TABLE IF NOT EXISTS movimientos_inventario (
    id_movimiento_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimiento VARCHAR(40) NOT NULL,
    fecha_movimiento TIMESTAMP(6) NOT NULL,
    id_equipo INTEGER,
    id_consumible INTEGER,
    cantidad INTEGER,
    id_bodega_origen INTEGER,
    id_bodega_destino INTEGER,
    id_custodio INTEGER,
    id_orden_compra INTEGER,
    estado_anterior VARCHAR(50),
    estado_nuevo VARCHAR(50),
    observacion TEXT,
    CONSTRAINT fk_mov_inv_equipo
        FOREIGN KEY (id_equipo) REFERENCES equipos (id_equipo),
    CONSTRAINT fk_mov_inv_consumible
        FOREIGN KEY (id_consumible) REFERENCES consumibles (id_consumible),
    CONSTRAINT fk_mov_inv_bodega_origen
        FOREIGN KEY (id_bodega_origen) REFERENCES bodegas (id_bodega),
    CONSTRAINT fk_mov_inv_bodega_destino
        FOREIGN KEY (id_bodega_destino) REFERENCES bodegas (id_bodega),
    CONSTRAINT fk_mov_inv_custodio
        FOREIGN KEY (id_custodio) REFERENCES custodios (id_custodio),
    CONSTRAINT fk_mov_inv_orden_compra
        FOREIGN KEY (id_orden_compra) REFERENCES ordenes_compra (id_orden_compra)
);

CREATE INDEX IF NOT EXISTS ix_ordenes_compra_bodega_destino ON ordenes_compra (id_bodega_destino);
CREATE INDEX IF NOT EXISTS ix_oc_detalle_orden ON ordenes_compra_detalle (id_orden_compra);
CREATE INDEX IF NOT EXISTS ix_stock_bodega ON stock_consumible_bodega (id_bodega);
CREATE INDEX IF NOT EXISTS ix_stock_consumible ON stock_consumible_bodega (id_consumible);
CREATE INDEX IF NOT EXISTS ix_mov_inv_fecha ON movimientos_inventario (fecha_movimiento);
CREATE INDEX IF NOT EXISTS ix_mov_inv_tipo ON movimientos_inventario (tipo_movimiento);
CREATE INDEX IF NOT EXISTS ix_mov_inv_equipo ON movimientos_inventario (id_equipo);
CREATE INDEX IF NOT EXISTS ix_mov_inv_consumible ON movimientos_inventario (id_consumible);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_equipos_bodega_actual'
    ) THEN
        ALTER TABLE equipos
            ADD CONSTRAINT fk_equipos_bodega_actual
            FOREIGN KEY (id_bodega_actual) REFERENCES bodegas (id_bodega);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_equipos_orden_compra'
    ) THEN
        ALTER TABLE equipos
            ADD CONSTRAINT fk_equipos_orden_compra
            FOREIGN KEY (id_orden_compra) REFERENCES ordenes_compra (id_orden_compra);
    END IF;
END $$;
