-- FASE 1: Base técnica para recepción de Ordenes de Compra
-- Amplía tablas existentes, migra datos y crea recepciones_lote.

-- 1. Ampliar ordenes_compra
ALTER TABLE ordenes_compra
    ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE,
    ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;

-- 2. Ampliar ordenes_compra_detalle (añadir estado, auditoría y campos de recepción)
ALTER TABLE ordenes_compra_detalle
    ADD COLUMN IF NOT EXISTS estado          VARCHAR(30)    NOT NULL DEFAULT 'PENDIENTE',
    ADD COLUMN IF NOT EXISTS observacion     TEXT,
    ADD COLUMN IF NOT EXISTS version         INTEGER        NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS modelo          VARCHAR(120),
    ADD COLUMN IF NOT EXISTS precio_unitario NUMERIC(14, 2),
    ADD COLUMN IF NOT EXISTS unidad_medida   VARCHAR(30),
    ADD COLUMN IF NOT EXISTS created_at      TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS created_by      VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_by      VARCHAR(100),
    ADD COLUMN IF NOT EXISTS deleted_at      TIMESTAMP(6);

-- 3. Migrar estado obsoleto en ordenes_compra
UPDATE ordenes_compra SET estado = 'RECEPCION_PARCIAL' WHERE estado = 'RECIBIDA_PARCIAL';

-- 4. Ampliar equipos con referencias a detalle OC y lote de recepción
ALTER TABLE equipos
    ADD COLUMN IF NOT EXISTS id_orden_compra_detalle INTEGER,
    ADD COLUMN IF NOT EXISTS id_recepcion_lote       INTEGER,
    ADD COLUMN IF NOT EXISTS condicion_al_recibir    VARCHAR(30);

-- 5. Ampliar movimientos_inventario con referencia al lote de recepción
ALTER TABLE movimientos_inventario
    ADD COLUMN IF NOT EXISTS id_recepcion_lote INTEGER;

-- 6. Nueva tabla recepciones_lote
CREATE TABLE IF NOT EXISTS recepciones_lote (
    id_recepcion_lote       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden_compra         INTEGER       NOT NULL,
    id_orden_compra_detalle INTEGER       NOT NULL,
    numero_lote             VARCHAR(60),
    fecha_recepcion         TIMESTAMP(6) NOT NULL,
    cantidad_recibida       INTEGER       NOT NULL,
    tipo_item               VARCHAR(20)   NOT NULL,
    estado                  VARCHAR(30)   NOT NULL,
    observacion             TEXT,
    id_bodega_destino       INTEGER,
    id_custodio_receptor    INTEGER,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    created_by              VARCHAR(100),
    updated_by              VARCHAR(100),
    deleted_at              TIMESTAMP(6),
    CONSTRAINT fk_rl_orden_compra       FOREIGN KEY (id_orden_compra)         REFERENCES ordenes_compra (id_orden_compra),
    CONSTRAINT fk_rl_orden_detalle      FOREIGN KEY (id_orden_compra_detalle) REFERENCES ordenes_compra_detalle (id_orden_compra_detalle),
    CONSTRAINT fk_rl_bodega_destino     FOREIGN KEY (id_bodega_destino)       REFERENCES bodegas (id_bodega),
    CONSTRAINT fk_rl_custodio_receptor  FOREIGN KEY (id_custodio_receptor)    REFERENCES custodios (id_custodio)
);

-- 7. FK nuevas en equipos (idempotentes)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_equipos_oc_detalle') THEN
        ALTER TABLE equipos
            ADD CONSTRAINT fk_equipos_oc_detalle
            FOREIGN KEY (id_orden_compra_detalle) REFERENCES ordenes_compra_detalle (id_orden_compra_detalle);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_equipos_recepcion_lote') THEN
        ALTER TABLE equipos
            ADD CONSTRAINT fk_equipos_recepcion_lote
            FOREIGN KEY (id_recepcion_lote) REFERENCES recepciones_lote (id_recepcion_lote);
    END IF;
END $$;

-- 8. FK nueva en movimientos_inventario (idempotente)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mov_recepcion_lote') THEN
        ALTER TABLE movimientos_inventario
            ADD CONSTRAINT fk_mov_recepcion_lote
            FOREIGN KEY (id_recepcion_lote) REFERENCES recepciones_lote (id_recepcion_lote);
    END IF;
END $$;

-- 9. Índices
CREATE INDEX IF NOT EXISTS ix_rl_orden_compra ON recepciones_lote (id_orden_compra);
CREATE INDEX IF NOT EXISTS ix_rl_detalle      ON recepciones_lote (id_orden_compra_detalle);
CREATE INDEX IF NOT EXISTS ix_rl_estado       ON recepciones_lote (estado);
CREATE INDEX IF NOT EXISTS ix_oc_detalle_estado ON ordenes_compra_detalle (estado);
