ALTER TABLE equipos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE equipos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE equipos ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE equipos ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE custodios ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE custodios ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE custodios ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE custodios ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE custodias ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE custodias ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE custodias ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE custodias ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE ubicaciones ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE ubicaciones ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE ubicaciones ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE ubicaciones ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE departamentos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE departamentos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE departamentos ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE departamentos ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE cargos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE cargos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE cargos ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE cargos ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE marcas ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE marcas ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE marcas ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE marcas ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE categorias_equipo ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE categorias_equipo ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE categorias_equipo ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE categorias_equipo ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);
