-- Sincronizacion de empleados desde fuente externa (JSON).
-- Los custodios son la tabla local de empleados: la sync hace upsert por cedula.

ALTER TABLE custodios ADD COLUMN IF NOT EXISTS origen_sync boolean NOT NULL DEFAULT false;
ALTER TABLE custodios ADD COLUMN IF NOT EXISTS sincronizado_en timestamp;

-- Registro de cada corrida de sincronizacion (fecha de ultima sync + contadores)
CREATE TABLE IF NOT EXISTS sync_empleados_ejecucion (
    id_ejecucion    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ejecutado_en    timestamp    NOT NULL,
    origen          varchar(20)  NOT NULL,
    ejecutado_por   varchar(100),
    total_recibidos integer      NOT NULL DEFAULT 0,
    creados         integer      NOT NULL DEFAULT 0,
    actualizados    integer      NOT NULL DEFAULT 0,
    inactivados     integer      NOT NULL DEFAULT 0,
    reactivados     integer      NOT NULL DEFAULT 0,
    sin_cambios     integer      NOT NULL DEFAULT 0,
    advertencias    integer      NOT NULL DEFAULT 0
);

-- Cambios relevantes detectados en cada corrida
CREATE TABLE IF NOT EXISTS sync_empleados_cambio (
    id_cambio    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ejecucion integer      NOT NULL REFERENCES sync_empleados_ejecucion(id_ejecucion),
    cedula       varchar(20)  NOT NULL,
    tipo         varchar(30)  NOT NULL,
    detalle      varchar(500),
    id_custodio  integer      REFERENCES custodios(id_custodio)
);

CREATE INDEX IF NOT EXISTS idx_sync_empleados_cambio_ejecucion
    ON sync_empleados_cambio(id_ejecucion);
