package com.uisrael.consumogestionactivosapi.service;

import java.util.List;

import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.BodegaRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.RegistrarRecepcionActivoRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.RegistrarRecepcionStockRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.RecepcionLoteResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.AsignacionActivoRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.AsignacionLoteRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.AsignacionConsumibleRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.BajaActivoRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.ConsumibleRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.DevolucionActivoRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.DevolucionConsumibleRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.EnviarConOtRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.EnviarReparacionRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.OrdenCompraRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.RetornarReparacionRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.RetornarYCerrarRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.ConfirmarLlegadaActivoRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.AdoptarInventarioInicialRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.RegistrarEtiquetaRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.TrasladoActivoRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.request.inventario.TrasladoConsumibleRequestDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.ActivoInventarioResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.AsignacionActivosResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.BodegaResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.ConsumibleResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.MovimientoInventarioResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.MovimientoPageResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.OrdenCompraResponseDTO;
import com.uisrael.consumogestionactivosapi.modelo.dto.response.inventario.StockConsumibleResponseDTO;

public interface IInventarioOperacionServicio {
    List<BodegaResponseDTO> listarBodegas();
    BodegaResponseDTO crearBodega(BodegaRequestDTO request);
    List<ConsumibleResponseDTO> listarConsumibles();
    ConsumibleResponseDTO crearConsumible(ConsumibleRequestDTO request);
    ConsumibleResponseDTO actualizarConsumible(Integer idConsumible, ConsumibleRequestDTO request);
    ConsumibleResponseDTO cambiarEstadoConsumible(Integer idConsumible, boolean estado);
    List<OrdenCompraResponseDTO> listarOrdenesCompra();
    OrdenCompraResponseDTO obtenerOrdenCompra(Integer id);
    OrdenCompraResponseDTO crearOrdenCompra(OrdenCompraRequestDTO request);
    OrdenCompraResponseDTO confirmarRecepcionOrden(Integer ordenCompraId);
    OrdenCompraResponseDTO cancelarOrdenCompra(Integer ordenCompraId);
    List<StockConsumibleResponseDTO> listarStockPorBodega(Integer bodegaId);
    List<MovimientoInventarioResponseDTO> listarMovimientosRecientes();
    MovimientoInventarioResponseDTO obtenerMovimiento(Integer id);
    MovimientoPageResponseDTO buscarMovimientos(Integer page, Integer size, String tipo,
            String fechaDesde, String fechaHasta, String equipoCodigo);
    List<ActivoInventarioResponseDTO> listarActivosEnBodega();
    List<ActivoInventarioResponseDTO> listarActivosAsignados();
    ActivoInventarioResponseDTO asignarActivo(AsignacionActivoRequestDTO request);
    AsignacionActivosResponseDTO asignarActivosLote(AsignacionLoteRequestDTO request);
    StockConsumibleResponseDTO asignarConsumible(AsignacionConsumibleRequestDTO request);
    ActivoInventarioResponseDTO devolverActivo(DevolucionActivoRequestDTO request);
    StockConsumibleResponseDTO devolverConsumible(DevolucionConsumibleRequestDTO request);
    ActivoInventarioResponseDTO trasladarActivo(TrasladoActivoRequestDTO request);
    StockConsumibleResponseDTO trasladarConsumible(TrasladoConsumibleRequestDTO request);
    ActivoInventarioResponseDTO darBajaActivo(BajaActivoRequestDTO request);
    ActivoInventarioResponseDTO enviarAReparacion(EnviarReparacionRequestDTO request);
    ActivoInventarioResponseDTO retornarDeReparacion(RetornarReparacionRequestDTO request);
    ActivoInventarioResponseDTO enviarConOt(EnviarConOtRequestDTO request);
    ActivoInventarioResponseDTO retornarYCerrar(RetornarYCerrarRequestDTO request);
    List<ActivoInventarioResponseDTO> listarActivosEnReparacion();
    List<ActivoInventarioResponseDTO> listarActivosEnTransito();
    ActivoInventarioResponseDTO confirmarLlegadaActivo(ConfirmarLlegadaActivoRequestDTO request);
    List<RecepcionLoteResponseDTO> listarRecepciones(Integer idOrdenCompra);
    RecepcionLoteResponseDTO registrarRecepcionStock(Integer idOrdenCompra, Integer idDetalle, RegistrarRecepcionStockRequestDTO request);
    RecepcionLoteResponseDTO registrarRecepcionActivo(Integer idOrdenCompra, Integer idDetalle, RegistrarRecepcionActivoRequestDTO request);
    ActivoInventarioResponseDTO registrarEtiqueta(Integer idEquipo, RegistrarEtiquetaRequestDTO request);
    List<ActivoInventarioResponseDTO> listarSinInventario();
    ActivoInventarioResponseDTO adoptarInventarioInicial(Integer idEquipo, AdoptarInventarioInicialRequestDTO request);
}
