spring.application.name=gestionactivosapi
spring.datasource.url=jdbc:postgresql://localhost:5432/cresio
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:.r4e3w2q1}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.devtools.restart.enabled=false

server.port=8082
actas.storage.base-path=${ACTAS_BASE_PATH:./data/actas}
actas.templates.asignacion-path=${ACTAS_TEMPLATE_ASIGNACION:./templates/acta-asignacion.docx}
actas.templates.traslado-path=${ACTAS_TEMPLATE_TRASLADO:./templates/acta-traslado.docx}
actas.templates.baja-path=${ACTAS_TEMPLATE_BAJA:./templates/acta-baja.docx}
mantenimiento.storage.base-path=${MANTENIMIENTO_STORAGE_PATH:./data/mantenimientos}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:ronald.moreno.cresio@gmail.com}
spring.mail.password=${MAIL_PASSWORD:gfmm ldbi jhxk sopa }
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_SMTP_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_SMTP_WRITE_TIMEOUT:5000}
app.mail.from-name=${MAIL_FROM_NAME:CRESIO - Gestion de Activos}
