
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=false

logging.level.com.uisrael.gestionactivosapi=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Mail deshabilitado en dev (sin SMTP configurado)
spring.mail.username=
spring.mail.password=
spring.mail.host=
