# ═══════════════════════════════════════════
# Perfil DEV — gestionactivosapi
# ═══════════════════════════════════════════
# Activar con: spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=false

logging.level.com.uisrael.gestionactivosapi=DEBUG
logging.level.org.hibernate.SQL=DEBUG
