--
-- PostgreSQL database dump
--

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-31 09:54:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 35316)
-- Name: actividades_checklist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividades_checklist (
    id_actividad integer NOT NULL,
    estado boolean,
    nombre character varying(200) NOT NULL,
    orden integer
);


ALTER TABLE public.actividades_checklist OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 35315)
-- Name: actividades_checklist_id_actividad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividades_checklist ALTER COLUMN id_actividad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividades_checklist_id_actividad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 35324)
-- Name: actividades_planificadas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividades_planificadas (
    id_actividad_planificada bigint NOT NULL,
    actualizado_en timestamp(6) without time zone,
    creado_en timestamp(6) without time zone,
    creado_por_id integer NOT NULL,
    descripcion text,
    estado character varying(30) NOT NULL,
    fecha_completada timestamp(6) without time zone,
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    fk_equipo integer,
    fk_mantenimiento_prog bigint,
    observaciones text,
    prioridad character varying(20) NOT NULL,
    referencia_mantenimiento_id integer,
    tecnico_id integer NOT NULL,
    tiempo_estimado_minutos integer,
    tiempo_real_minutos integer,
    tipo_actividad character varying(50) NOT NULL,
    titulo character varying(200) NOT NULL
);


ALTER TABLE public.actividades_planificadas OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 35323)
-- Name: actividades_planificadas_id_actividad_planificada_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividades_planificadas ALTER COLUMN id_actividad_planificada ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividades_planificadas_id_actividad_planificada_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 35341)
-- Name: actividades_realizadas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividades_realizadas (
    id_actividad_realizada integer NOT NULL,
    id_actividad integer NOT NULL,
    id_mantenimiento integer NOT NULL,
    realizada boolean
);


ALTER TABLE public.actividades_realizadas OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 35340)
-- Name: actividades_realizadas_id_actividad_realizada_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividades_realizadas ALTER COLUMN id_actividad_realizada ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividades_realizadas_id_actividad_realizada_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 35350)
-- Name: activos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activos (
    id_activo integer NOT NULL,
    descripcion text,
    estado character varying(255),
    fecha_adquisicion date,
    fk_categoria integer,
    fk_departamento integer,
    fk_ubicacion integer,
    modelo character varying(255),
    nombre character varying(255) NOT NULL,
    serie character varying(255),
    valor_actual double precision
);


ALTER TABLE public.activos OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 35349)
-- Name: activos_id_activo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activos ALTER COLUMN id_activo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activos_id_activo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 35360)
-- Name: actualizacion_activos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actualizacion_activos (
    id integer NOT NULL,
    activo_id integer NOT NULL,
    descripcion text,
    fecha_actualizacion timestamp(6) without time zone,
    fk_usuario_actualizacion integer
);


ALTER TABLE public.actualizacion_activos OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 35359)
-- Name: actualizacion_activos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actualizacion_activos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actualizacion_activos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 35370)
-- Name: cargos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cargos (
    id_cargo integer NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    fk_departamento integer
);


ALTER TABLE public.cargos OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 35369)
-- Name: cargos_id_cargo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cargos ALTER COLUMN id_cargo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cargos_id_cargo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 35379)
-- Name: categorias_equipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias_equipo (
    id_categoria integer NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.categorias_equipo OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 35378)
-- Name: categorias_equipo_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias_equipo ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_equipo_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 35387)
-- Name: checklist_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.checklist_categoria (
    id_actividad integer NOT NULL,
    id_categoria integer NOT NULL
);


ALTER TABLE public.checklist_categoria OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 35395)
-- Name: consentimiento_monitoreo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consentimiento_monitoreo (
    id_consentimiento bigint NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    creado_en timestamp(6) without time zone,
    fecha_aceptacion timestamp(6) without time zone NOT NULL,
    ip_aceptacion character varying(45),
    usuario_id integer NOT NULL,
    version_terminos character varying(20) DEFAULT '1.0'::character varying NOT NULL
);


ALTER TABLE public.consentimiento_monitoreo OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 35394)
-- Name: consentimiento_monitoreo_id_consentimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consentimiento_monitoreo ALTER COLUMN id_consentimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consentimiento_monitoreo_id_consentimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 35408)
-- Name: custodias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.custodias (
    id_custodia_equipo integer NOT NULL,
    estado boolean NOT NULL,
    fecha_fin date,
    fecha_inicio date,
    observacion character varying(255),
    tipo_movimiento character varying(255),
    id_custodio integer NOT NULL,
    id_equipo integer NOT NULL,
    fk_ubicacion integer
);


ALTER TABLE public.custodias OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 35407)
-- Name: custodias_id_custodia_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.custodias ALTER COLUMN id_custodia_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custodias_id_custodia_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 35420)
-- Name: custodios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.custodios (
    id_custodio integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(100),
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    updated_by character varying(100),
    cedula character varying(20) NOT NULL,
    correo character varying(150),
    estado boolean NOT NULL,
    fecha_ingreso date,
    nombre character varying(100) NOT NULL,
    telefono character varying(20),
    fk_cargo integer,
    fk_ubicacion integer,
    fk_usuario integer
);


ALTER TABLE public.custodios OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 35419)
-- Name: custodios_id_custodio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.custodios ALTER COLUMN id_custodio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custodios_id_custodio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 35432)
-- Name: departamentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamentos (
    id_departamento integer NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    fk_ubicacion integer
);


ALTER TABLE public.departamentos OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 35431)
-- Name: departamentos_id_departamento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departamentos ALTER COLUMN id_departamento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamentos_id_departamento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 35441)
-- Name: empresas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresas (
    id_empresa integer NOT NULL,
    actualizado_en timestamp(6) without time zone NOT NULL,
    correo character varying(150),
    creado_en timestamp(6) without time zone NOT NULL,
    direccion character varying(500),
    eliminado_en timestamp(6) without time zone,
    estado boolean NOT NULL,
    nombre character varying(200) NOT NULL,
    ruc character varying(13) NOT NULL,
    telefono character varying(20)
);


ALTER TABLE public.empresas OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 35440)
-- Name: empresas_id_empresa_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresas ALTER COLUMN id_empresa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresas_id_empresa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 35455)
-- Name: equipos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipos (
    id_equipo integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(100),
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    updated_by character varying(100),
    capacidad_almacenamiento_gb integer,
    codigo_sap character varying(20),
    estado boolean NOT NULL,
    estado_equipo character varying(50),
    etiqueta_activo_fijo boolean,
    fecha_compra date,
    ip character varying(100),
    licencia_windows_activada boolean,
    mac character varying(100),
    memoria_ram_gb integer,
    modelo character varying(100),
    observacion_equipo text,
    precio_compra numeric(10,2),
    procesador character varying(100),
    serial character varying(100),
    sistema_operativo character varying(100),
    tipo_equipo character varying(100),
    tipo_licencia_office character varying(50),
    union_dominio boolean,
    version_office character varying(150),
    id_categoria integer NOT NULL,
    id_marca integer NOT NULL,
    fk_ubicacion integer
);


ALTER TABLE public.equipos OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 35454)
-- Name: equipos_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipos ALTER COLUMN id_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipos_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 35467)
-- Name: firmas_mantenimiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.firmas_mantenimiento (
    id integer NOT NULL,
    firma_base64 text NOT NULL,
    firmado_en timestamp(6) without time zone NOT NULL,
    firmado_por_id integer,
    id_mantenimiento integer NOT NULL,
    ip_origen character varying(45),
    tipo_firma character varying(20) NOT NULL,
    CONSTRAINT firmas_mantenimiento_tipo_firma_check CHECK (((tipo_firma)::text = ANY ((ARRAY['CUSTODIO'::character varying, 'TECNICO'::character varying])::text[])))
);


ALTER TABLE public.firmas_mantenimiento OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 35466)
-- Name: firmas_mantenimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.firmas_mantenimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.firmas_mantenimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 35481)
-- Name: imagenes_mantenimiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imagenes_mantenimiento (
    id_imagen bigint NOT NULL,
    id_mantenimiento integer NOT NULL,
    nombre_archivo character varying(255) NOT NULL,
    ruta_archivo character varying(500) NOT NULL,
    tamanio_bytes bigint
);


ALTER TABLE public.imagenes_mantenimiento OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 35480)
-- Name: imagenes_mantenimiento_id_imagen_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imagenes_mantenimiento ALTER COLUMN id_imagen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagenes_mantenimiento_id_imagen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 35493)
-- Name: mantenimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mantenimientos (
    id_mantenimiento integer NOT NULL,
    activo boolean,
    creado_en timestamp(6) without time zone,
    descripcion character varying(2000),
    empresa_id integer,
    equipo_id integer NOT NULL,
    codigo_interno_snapshot character varying(50),
    serie_snapshot character varying(120),
    year_snapshoted integer,
    estado character varying(30),
    estado_general character varying(20),
    estado_interno character varying(30),
    fec_cierre timestamp(6) without time zone,
    fecha_programada timestamp(6) without time zone NOT NULL,
    fk_programado integer,
    cliente_id integer,
    id_usuario integer,
    odoo_ticket_id character varying(50),
    proxima_fecha date,
    tipo_mantenimiento character varying(30),
    tipo_origen character varying(30),
    CONSTRAINT mantenimientos_estado_interno_check CHECK (((estado_interno)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'EN_PROCESO'::character varying, 'CERRADO'::character varying, 'CANCELADO'::character varying])::text[]))),
    CONSTRAINT mantenimientos_tipo_origen_check CHECK (((tipo_origen)::text = ANY ((ARRAY['ODOO_HELPDESK'::character varying, 'PROGRAMADO'::character varying, 'MANUAL'::character varying])::text[])))
);


ALTER TABLE public.mantenimientos OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 35492)
-- Name: mantenimientos_id_mantenimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mantenimientos ALTER COLUMN id_mantenimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mantenimientos_id_mantenimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 35506)
-- Name: mantenimientos_programados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mantenimientos_programados (
    id_programado bigint NOT NULL,
    equipo_id integer NOT NULL,
    estado boolean,
    fecha_proximo_mantenimiento date NOT NULL,
    fecha_ultimo_mantenimiento date,
    frecuencia_dias integer NOT NULL,
    observaciones text,
    tecnico_id integer NOT NULL
);


ALTER TABLE public.mantenimientos_programados OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 35505)
-- Name: mantenimientos_programados_id_programado_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mantenimientos_programados ALTER COLUMN id_programado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mantenimientos_programados_id_programado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 35519)
-- Name: marcas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marcas (
    id_marca integer NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.marcas OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 35518)
-- Name: marcas_id_marca_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marcas ALTER COLUMN id_marca ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marcas_id_marca_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 35528)
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones (
    id_notificacion bigint NOT NULL,
    creado_en timestamp(6) without time zone,
    leida boolean,
    mensaje character varying(255) NOT NULL,
    referencia_actividad_id bigint,
    referencia_mantenimiento_id integer,
    url character varying(500),
    usuario_id integer NOT NULL
);


ALTER TABLE public.notificaciones OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 35527)
-- Name: notificaciones_id_notificacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones ALTER COLUMN id_notificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_notificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 35539)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id_rol integer NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 35538)
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 35548)
-- Name: ubicaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ubicaciones (
    id_ubicacion integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(100),
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    updated_by character varying(100),
    agencia character varying(100) NOT NULL,
    ciudad character varying(100),
    direccion character varying(255),
    estado boolean NOT NULL,
    latitud numeric(10,7),
    link_coordenada character varying(500),
    longitud numeric(10,7),
    nombre character varying(100) NOT NULL,
    parroquia character varying(150),
    provincia character varying(100)
);


ALTER TABLE public.ubicaciones OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 35547)
-- Name: ubicaciones_id_ubicacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ubicaciones ALTER COLUMN id_ubicacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ubicaciones_id_ubicacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 35560)
-- Name: ubicaciones_tecnicos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ubicaciones_tecnicos (
    id_ubicacion_tecnico bigint NOT NULL,
    creado_en timestamp(6) without time zone,
    latitud numeric(10,7) NOT NULL,
    longitud numeric(10,7) NOT NULL,
    precision_metros numeric(6,2),
    timestamp_captura timestamp(6) without time zone NOT NULL,
    usuario_id integer NOT NULL
);


ALTER TABLE public.ubicaciones_tecnicos OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 35559)
-- Name: ubicaciones_tecnicos_id_ubicacion_tecnico_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ubicaciones_tecnicos ALTER COLUMN id_ubicacion_tecnico ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ubicaciones_tecnicos_id_ubicacion_tecnico_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 35571)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(100),
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    updated_by character varying(100),
    cedula character varying(20),
    contrasena character varying(255) NOT NULL,
    correo character varying(150) NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    id_departamento integer,
    id_rol integer
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 35570)
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5214 (class 0 OID 35316)
-- Dependencies: 220
-- Data for Name: actividades_checklist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividades_checklist (id_actividad, estado, nombre, orden) FROM stdin;
\.


--
-- TOC entry 5216 (class 0 OID 35324)
-- Dependencies: 222
-- Data for Name: actividades_planificadas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividades_planificadas (id_actividad_planificada, actualizado_en, creado_en, creado_por_id, descripcion, estado, fecha_completada, fecha_fin, fecha_inicio, fk_equipo, fk_mantenimiento_prog, observaciones, prioridad, referencia_mantenimiento_id, tecnico_id, tiempo_estimado_minutos, tiempo_real_minutos, tipo_actividad, titulo) FROM stdin;
\.


--
-- TOC entry 5218 (class 0 OID 35341)
-- Dependencies: 224
-- Data for Name: actividades_realizadas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividades_realizadas (id_actividad_realizada, id_actividad, id_mantenimiento, realizada) FROM stdin;
\.


--
-- TOC entry 5220 (class 0 OID 35350)
-- Dependencies: 226
-- Data for Name: activos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activos (id_activo, descripcion, estado, fecha_adquisicion, fk_categoria, fk_departamento, fk_ubicacion, modelo, nombre, serie, valor_actual) FROM stdin;
\.


--
-- TOC entry 5222 (class 0 OID 35360)
-- Dependencies: 228
-- Data for Name: actualizacion_activos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actualizacion_activos (id, activo_id, descripcion, fecha_actualizacion, fk_usuario_actualizacion) FROM stdin;
\.


--
-- TOC entry 5224 (class 0 OID 35370)
-- Dependencies: 230
-- Data for Name: cargos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cargos (id_cargo, estado, nombre, fk_departamento) FROM stdin;
\.


--
-- TOC entry 5226 (class 0 OID 35379)
-- Dependencies: 232
-- Data for Name: categorias_equipo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categorias_equipo (id_categoria, estado, nombre) FROM stdin;
\.


--
-- TOC entry 5227 (class 0 OID 35387)
-- Dependencies: 233
-- Data for Name: checklist_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.checklist_categoria (id_actividad, id_categoria) FROM stdin;
\.


--
-- TOC entry 5229 (class 0 OID 35395)
-- Dependencies: 235
-- Data for Name: consentimiento_monitoreo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.consentimiento_monitoreo (id_consentimiento, activo, creado_en, fecha_aceptacion, ip_aceptacion, usuario_id, version_terminos) FROM stdin;
\.


--
-- TOC entry 5231 (class 0 OID 35408)
-- Dependencies: 237
-- Data for Name: custodias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.custodias (id_custodia_equipo, estado, fecha_fin, fecha_inicio, observacion, tipo_movimiento, id_custodio, id_equipo, fk_ubicacion) FROM stdin;
\.


--
-- TOC entry 5233 (class 0 OID 35420)
-- Dependencies: 239
-- Data for Name: custodios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.custodios (id_custodio, created_at, created_by, deleted_at, updated_at, updated_by, cedula, correo, estado, fecha_ingreso, nombre, telefono, fk_cargo, fk_ubicacion, fk_usuario) FROM stdin;
\.


--
-- TOC entry 5235 (class 0 OID 35432)
-- Dependencies: 241
-- Data for Name: departamentos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departamentos (id_departamento, estado, nombre, fk_ubicacion) FROM stdin;
\.


--
-- TOC entry 5237 (class 0 OID 35441)
-- Dependencies: 243
-- Data for Name: empresas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empresas (id_empresa, actualizado_en, correo, creado_en, direccion, eliminado_en, estado, nombre, ruc, telefono) FROM stdin;
\.


--
-- TOC entry 5239 (class 0 OID 35455)
-- Dependencies: 245
-- Data for Name: equipos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipos (id_equipo, created_at, created_by, deleted_at, updated_at, updated_by, capacidad_almacenamiento_gb, codigo_sap, estado, estado_equipo, etiqueta_activo_fijo, fecha_compra, ip, licencia_windows_activada, mac, memoria_ram_gb, modelo, observacion_equipo, precio_compra, procesador, serial, sistema_operativo, tipo_equipo, tipo_licencia_office, union_dominio, version_office, id_categoria, id_marca, fk_ubicacion) FROM stdin;
\.


--
-- TOC entry 5241 (class 0 OID 35467)
-- Dependencies: 247
-- Data for Name: firmas_mantenimiento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.firmas_mantenimiento (id, firma_base64, firmado_en, firmado_por_id, id_mantenimiento, ip_origen, tipo_firma) FROM stdin;
\.


--
-- TOC entry 5243 (class 0 OID 35481)
-- Dependencies: 249
-- Data for Name: imagenes_mantenimiento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.imagenes_mantenimiento (id_imagen, id_mantenimiento, nombre_archivo, ruta_archivo, tamanio_bytes) FROM stdin;
\.


--
-- TOC entry 5245 (class 0 OID 35493)
-- Dependencies: 251
-- Data for Name: mantenimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mantenimientos (id_mantenimiento, activo, creado_en, descripcion, empresa_id, equipo_id, codigo_interno_snapshot, serie_snapshot, year_snapshoted, estado, estado_general, estado_interno, fec_cierre, fecha_programada, fk_programado, cliente_id, id_usuario, odoo_ticket_id, proxima_fecha, tipo_mantenimiento, tipo_origen) FROM stdin;
\.


--
-- TOC entry 5247 (class 0 OID 35506)
-- Dependencies: 253
-- Data for Name: mantenimientos_programados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mantenimientos_programados (id_programado, equipo_id, estado, fecha_proximo_mantenimiento, fecha_ultimo_mantenimiento, frecuencia_dias, observaciones, tecnico_id) FROM stdin;
\.


--
-- TOC entry 5249 (class 0 OID 35519)
-- Dependencies: 255
-- Data for Name: marcas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marcas (id_marca, estado, nombre) FROM stdin;
\.


--
-- TOC entry 5251 (class 0 OID 35528)
-- Dependencies: 257
-- Data for Name: notificaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notificaciones (id_notificacion, creado_en, leida, mensaje, referencia_actividad_id, referencia_mantenimiento_id, url, usuario_id) FROM stdin;
\.


--
-- TOC entry 5253 (class 0 OID 35539)
-- Dependencies: 259
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id_rol, estado, nombre) FROM stdin;
\.


--
-- TOC entry 5255 (class 0 OID 35548)
-- Dependencies: 261
-- Data for Name: ubicaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ubicaciones (id_ubicacion, created_at, created_by, deleted_at, updated_at, updated_by, agencia, ciudad, direccion, estado, latitud, link_coordenada, longitud, nombre, parroquia, provincia) FROM stdin;
\.


--
-- TOC entry 5257 (class 0 OID 35560)
-- Dependencies: 263
-- Data for Name: ubicaciones_tecnicos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ubicaciones_tecnicos (id_ubicacion_tecnico, creado_en, latitud, longitud, precision_metros, timestamp_captura, usuario_id) FROM stdin;
\.


--
-- TOC entry 5259 (class 0 OID 35571)
-- Dependencies: 265
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id_usuario, created_at, created_by, deleted_at, updated_at, updated_by, cedula, contrasena, correo, estado, nombre, id_departamento, id_rol) FROM stdin;
\.


--
-- TOC entry 5265 (class 0 OID 0)
-- Dependencies: 219
-- Name: actividades_checklist_id_actividad_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividades_checklist_id_actividad_seq', 1, false);


--
-- TOC entry 5266 (class 0 OID 0)
-- Dependencies: 221
-- Name: actividades_planificadas_id_actividad_planificada_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividades_planificadas_id_actividad_planificada_seq', 1, false);


--
-- TOC entry 5267 (class 0 OID 0)
-- Dependencies: 223
-- Name: actividades_realizadas_id_actividad_realizada_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividades_realizadas_id_actividad_realizada_seq', 1, false);


--
-- TOC entry 5268 (class 0 OID 0)
-- Dependencies: 225
-- Name: activos_id_activo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activos_id_activo_seq', 1, false);


--
-- TOC entry 5269 (class 0 OID 0)
-- Dependencies: 227
-- Name: actualizacion_activos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actualizacion_activos_id_seq', 1, false);


--
-- TOC entry 5270 (class 0 OID 0)
-- Dependencies: 229
-- Name: cargos_id_cargo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cargos_id_cargo_seq', 1, false);


--
-- TOC entry 5271 (class 0 OID 0)
-- Dependencies: 231
-- Name: categorias_equipo_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorias_equipo_id_categoria_seq', 1, false);


--
-- TOC entry 5272 (class 0 OID 0)
-- Dependencies: 234
-- Name: consentimiento_monitoreo_id_consentimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.consentimiento_monitoreo_id_consentimiento_seq', 1, false);


--
-- TOC entry 5273 (class 0 OID 0)
-- Dependencies: 236
-- Name: custodias_id_custodia_equipo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.custodias_id_custodia_equipo_seq', 1, false);


--
-- TOC entry 5274 (class 0 OID 0)
-- Dependencies: 238
-- Name: custodios_id_custodio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.custodios_id_custodio_seq', 1, false);


--
-- TOC entry 5275 (class 0 OID 0)
-- Dependencies: 240
-- Name: departamentos_id_departamento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departamentos_id_departamento_seq', 1, false);


--
-- TOC entry 5276 (class 0 OID 0)
-- Dependencies: 242
-- Name: empresas_id_empresa_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empresas_id_empresa_seq', 1, false);


--
-- TOC entry 5277 (class 0 OID 0)
-- Dependencies: 244
-- Name: equipos_id_equipo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipos_id_equipo_seq', 1, false);


--
-- TOC entry 5278 (class 0 OID 0)
-- Dependencies: 246
-- Name: firmas_mantenimiento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.firmas_mantenimiento_id_seq', 1, false);


--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 248
-- Name: imagenes_mantenimiento_id_imagen_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.imagenes_mantenimiento_id_imagen_seq', 1, false);


--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 250
-- Name: mantenimientos_id_mantenimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mantenimientos_id_mantenimiento_seq', 1, false);


--
-- TOC entry 5281 (class 0 OID 0)
-- Dependencies: 252
-- Name: mantenimientos_programados_id_programado_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mantenimientos_programados_id_programado_seq', 1, false);


--
-- TOC entry 5282 (class 0 OID 0)
-- Dependencies: 254
-- Name: marcas_id_marca_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marcas_id_marca_seq', 1, false);


--
-- TOC entry 5283 (class 0 OID 0)
-- Dependencies: 256
-- Name: notificaciones_id_notificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notificaciones_id_notificacion_seq', 1, false);


--
-- TOC entry 5284 (class 0 OID 0)
-- Dependencies: 258
-- Name: roles_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_rol_seq', 1, false);


--
-- TOC entry 5285 (class 0 OID 0)
-- Dependencies: 260
-- Name: ubicaciones_id_ubicacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ubicaciones_id_ubicacion_seq', 1, false);


--
-- TOC entry 5286 (class 0 OID 0)
-- Dependencies: 262
-- Name: ubicaciones_tecnicos_id_ubicacion_tecnico_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ubicaciones_tecnicos_id_ubicacion_tecnico_seq', 1, false);


--
-- TOC entry 5287 (class 0 OID 0)
-- Dependencies: 264
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 1, false);


--
-- TOC entry 4976 (class 2606 OID 35322)
-- Name: actividades_checklist actividades_checklist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_checklist
    ADD CONSTRAINT actividades_checklist_pkey PRIMARY KEY (id_actividad);


--
-- TOC entry 4978 (class 2606 OID 35339)
-- Name: actividades_planificadas actividades_planificadas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_planificadas
    ADD CONSTRAINT actividades_planificadas_pkey PRIMARY KEY (id_actividad_planificada);


--
-- TOC entry 4980 (class 2606 OID 35348)
-- Name: actividades_realizadas actividades_realizadas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_realizadas
    ADD CONSTRAINT actividades_realizadas_pkey PRIMARY KEY (id_actividad_realizada);


--
-- TOC entry 4982 (class 2606 OID 35358)
-- Name: activos activos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activos
    ADD CONSTRAINT activos_pkey PRIMARY KEY (id_activo);


--
-- TOC entry 4986 (class 2606 OID 35368)
-- Name: actualizacion_activos actualizacion_activos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actualizacion_activos
    ADD CONSTRAINT actualizacion_activos_pkey PRIMARY KEY (id);


--
-- TOC entry 4988 (class 2606 OID 35377)
-- Name: cargos cargos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cargos
    ADD CONSTRAINT cargos_pkey PRIMARY KEY (id_cargo);


--
-- TOC entry 4990 (class 2606 OID 35386)
-- Name: categorias_equipo categorias_equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias_equipo
    ADD CONSTRAINT categorias_equipo_pkey PRIMARY KEY (id_categoria);


--
-- TOC entry 4992 (class 2606 OID 35393)
-- Name: checklist_categoria checklist_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_categoria
    ADD CONSTRAINT checklist_categoria_pkey PRIMARY KEY (id_actividad, id_categoria);


--
-- TOC entry 4994 (class 2606 OID 35406)
-- Name: consentimiento_monitoreo consentimiento_monitoreo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consentimiento_monitoreo
    ADD CONSTRAINT consentimiento_monitoreo_pkey PRIMARY KEY (id_consentimiento);


--
-- TOC entry 4996 (class 2606 OID 35418)
-- Name: custodias custodias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodias
    ADD CONSTRAINT custodias_pkey PRIMARY KEY (id_custodia_equipo);


--
-- TOC entry 4998 (class 2606 OID 35430)
-- Name: custodios custodios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodios
    ADD CONSTRAINT custodios_pkey PRIMARY KEY (id_custodio);


--
-- TOC entry 5000 (class 2606 OID 35439)
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id_departamento);


--
-- TOC entry 5002 (class 2606 OID 35453)
-- Name: empresas empresas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id_empresa);


--
-- TOC entry 5006 (class 2606 OID 35465)
-- Name: equipos equipos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipos
    ADD CONSTRAINT equipos_pkey PRIMARY KEY (id_equipo);


--
-- TOC entry 5008 (class 2606 OID 35479)
-- Name: firmas_mantenimiento firmas_mantenimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firmas_mantenimiento
    ADD CONSTRAINT firmas_mantenimiento_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 35491)
-- Name: imagenes_mantenimiento imagenes_mantenimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagenes_mantenimiento
    ADD CONSTRAINT imagenes_mantenimiento_pkey PRIMARY KEY (id_imagen);


--
-- TOC entry 5012 (class 2606 OID 35504)
-- Name: mantenimientos mantenimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos
    ADD CONSTRAINT mantenimientos_pkey PRIMARY KEY (id_mantenimiento);


--
-- TOC entry 5014 (class 2606 OID 35517)
-- Name: mantenimientos_programados mantenimientos_programados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos_programados
    ADD CONSTRAINT mantenimientos_programados_pkey PRIMARY KEY (id_programado);


--
-- TOC entry 5016 (class 2606 OID 35526)
-- Name: marcas marcas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_pkey PRIMARY KEY (id_marca);


--
-- TOC entry 5018 (class 2606 OID 35537)
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id_notificacion);


--
-- TOC entry 5020 (class 2606 OID 35546)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_rol);


--
-- TOC entry 5022 (class 2606 OID 35558)
-- Name: ubicaciones ubicaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ubicaciones
    ADD CONSTRAINT ubicaciones_pkey PRIMARY KEY (id_ubicacion);


--
-- TOC entry 5024 (class 2606 OID 35569)
-- Name: ubicaciones_tecnicos ubicaciones_tecnicos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ubicaciones_tecnicos
    ADD CONSTRAINT ubicaciones_tecnicos_pkey PRIMARY KEY (id_ubicacion_tecnico);


--
-- TOC entry 5004 (class 2606 OID 35586)
-- Name: empresas ukd6avi1g5t06l7qo67kj8ty2j2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT ukd6avi1g5t06l7qo67kj8ty2j2 UNIQUE (ruc);


--
-- TOC entry 4984 (class 2606 OID 35584)
-- Name: activos ukgcx5lymdnsvji4lac0od1govt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activos
    ADD CONSTRAINT ukgcx5lymdnsvji4lac0od1govt UNIQUE (serie);


--
-- TOC entry 5026 (class 2606 OID 35582)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- TOC entry 5036 (class 2606 OID 35632)
-- Name: cargos fk156ptm0uj5txq9wfe38el6mg3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cargos
    ADD CONSTRAINT fk156ptm0uj5txq9wfe38el6mg3 FOREIGN KEY (fk_departamento) REFERENCES public.departamentos(id_departamento);


--
-- TOC entry 5060 (class 2606 OID 35762)
-- Name: notificaciones fk16afpmdf9tgjj859c0ak0i5al; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk16afpmdf9tgjj859c0ak0i5al FOREIGN KEY (referencia_actividad_id) REFERENCES public.actividades_planificadas(id_actividad_planificada);


--
-- TOC entry 5061 (class 2606 OID 35757)
-- Name: notificaciones fk1mxbjb81ft61gwlh0kabubndc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk1mxbjb81ft61gwlh0kabubndc FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5027 (class 2606 OID 35597)
-- Name: actividades_planificadas fk29ey84ng8x7unp5easofaw07q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_planificadas
    ADD CONSTRAINT fk29ey84ng8x7unp5easofaw07q FOREIGN KEY (referencia_mantenimiento_id) REFERENCES public.mantenimientos(id_mantenimiento);


--
-- TOC entry 5064 (class 2606 OID 35777)
-- Name: usuarios fk3kl77pehgupicftwfreqnjkll; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk3kl77pehgupicftwfreqnjkll FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol);


--
-- TOC entry 5028 (class 2606 OID 35607)
-- Name: actividades_planificadas fk421wid8o79m2ixhf6t77f51ec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_planificadas
    ADD CONSTRAINT fk421wid8o79m2ixhf6t77f51ec FOREIGN KEY (tecnico_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5037 (class 2606 OID 35642)
-- Name: checklist_categoria fk5xfsarwmawff61vc0b252lu9t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_categoria
    ADD CONSTRAINT fk5xfsarwmawff61vc0b252lu9t FOREIGN KEY (id_actividad) REFERENCES public.actividades_checklist(id_actividad);


--
-- TOC entry 5053 (class 2606 OID 35732)
-- Name: mantenimientos fk6hibihkuky5qeuxukbkfcf76j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos
    ADD CONSTRAINT fk6hibihkuky5qeuxukbkfcf76j FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5043 (class 2606 OID 35677)
-- Name: custodios fk6mtt22i139983sq4fwe0xjp8j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodios
    ADD CONSTRAINT fk6mtt22i139983sq4fwe0xjp8j FOREIGN KEY (fk_usuario) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5054 (class 2606 OID 35717)
-- Name: mantenimientos fk7uqalh2pefnhcjjljoj6yyiyh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos
    ADD CONSTRAINT fk7uqalh2pefnhcjjljoj6yyiyh FOREIGN KEY (cliente_id) REFERENCES public.custodios(id_custodio);


--
-- TOC entry 5047 (class 2606 OID 35692)
-- Name: equipos fk8h9wtrvbuf7hp7n3x3154l72u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipos
    ADD CONSTRAINT fk8h9wtrvbuf7hp7n3x3154l72u FOREIGN KEY (id_marca) REFERENCES public.marcas(id_marca);


--
-- TOC entry 5040 (class 2606 OID 35657)
-- Name: custodias fk8ibkm9a8g0r16sixu4hhyuca; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodias
    ADD CONSTRAINT fk8ibkm9a8g0r16sixu4hhyuca FOREIGN KEY (id_equipo) REFERENCES public.equipos(id_equipo);


--
-- TOC entry 5041 (class 2606 OID 35652)
-- Name: custodias fk8l5d7qgngmukr5w9qm3y0w5jp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodias
    ADD CONSTRAINT fk8l5d7qgngmukr5w9qm3y0w5jp FOREIGN KEY (id_custodio) REFERENCES public.custodios(id_custodio);


--
-- TOC entry 5029 (class 2606 OID 35587)
-- Name: actividades_planificadas fk8wvva9wefg1rthvwncgm66npb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_planificadas
    ADD CONSTRAINT fk8wvva9wefg1rthvwncgm66npb FOREIGN KEY (creado_por_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5044 (class 2606 OID 35667)
-- Name: custodios fk94uypj4505axa3t0h749tp417; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodios
    ADD CONSTRAINT fk94uypj4505axa3t0h749tp417 FOREIGN KEY (fk_cargo) REFERENCES public.cargos(id_cargo);


--
-- TOC entry 5038 (class 2606 OID 35637)
-- Name: checklist_categoria fkb6p5gsfw2ygdakaemsupdcrk4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_categoria
    ADD CONSTRAINT fkb6p5gsfw2ygdakaemsupdcrk4 FOREIGN KEY (id_categoria) REFERENCES public.categorias_equipo(id_categoria);


--
-- TOC entry 5055 (class 2606 OID 35727)
-- Name: mantenimientos fkc0ki116odpff030ci9pfytxwq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos
    ADD CONSTRAINT fkc0ki116odpff030ci9pfytxwq FOREIGN KEY (equipo_id) REFERENCES public.equipos(id_equipo);


--
-- TOC entry 5039 (class 2606 OID 35647)
-- Name: consentimiento_monitoreo fkc0taqo5xvutwb1r2ysuhv7ek2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consentimiento_monitoreo
    ADD CONSTRAINT fkc0taqo5xvutwb1r2ysuhv7ek2 FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5035 (class 2606 OID 35627)
-- Name: actualizacion_activos fkce6k5tr3hya3o2noeli5suds7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actualizacion_activos
    ADD CONSTRAINT fkce6k5tr3hya3o2noeli5suds7 FOREIGN KEY (fk_usuario_actualizacion) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5034 (class 2606 OID 35622)
-- Name: activos fkcgpbxbrnesngiggqvws48dugo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activos
    ADD CONSTRAINT fkcgpbxbrnesngiggqvws48dugo FOREIGN KEY (fk_ubicacion) REFERENCES public.ubicaciones(id_ubicacion);


--
-- TOC entry 5050 (class 2606 OID 35707)
-- Name: firmas_mantenimiento fkclasor73mrhjqxnl7i9pvw61f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firmas_mantenimiento
    ADD CONSTRAINT fkclasor73mrhjqxnl7i9pvw61f FOREIGN KEY (id_mantenimiento) REFERENCES public.mantenimientos(id_mantenimiento);


--
-- TOC entry 5030 (class 2606 OID 35592)
-- Name: actividades_planificadas fkcq05u2tqqam4dk30oqwx73mjm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_planificadas
    ADD CONSTRAINT fkcq05u2tqqam4dk30oqwx73mjm FOREIGN KEY (fk_equipo) REFERENCES public.equipos(id_equipo);


--
-- TOC entry 5058 (class 2606 OID 35742)
-- Name: mantenimientos_programados fkd26djjopn5ktubd88r87b6wij; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos_programados
    ADD CONSTRAINT fkd26djjopn5ktubd88r87b6wij FOREIGN KEY (equipo_id) REFERENCES public.equipos(id_equipo);


--
-- TOC entry 5063 (class 2606 OID 35767)
-- Name: ubicaciones_tecnicos fkd7ltrnfxt4ukac1ujv3029vwk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ubicaciones_tecnicos
    ADD CONSTRAINT fkd7ltrnfxt4ukac1ujv3029vwk FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5042 (class 2606 OID 35662)
-- Name: custodias fkg42ea2tbtq7jr4clrnrtdo8sp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodias
    ADD CONSTRAINT fkg42ea2tbtq7jr4clrnrtdo8sp FOREIGN KEY (fk_ubicacion) REFERENCES public.ubicaciones(id_ubicacion);


--
-- TOC entry 5051 (class 2606 OID 35702)
-- Name: firmas_mantenimiento fki1au4lxoekegp6kkceo3xj2qv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firmas_mantenimiento
    ADD CONSTRAINT fki1au4lxoekegp6kkceo3xj2qv FOREIGN KEY (firmado_por_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5065 (class 2606 OID 35772)
-- Name: usuarios fkildn8kon9kyb9m21cofwmx0uu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fkildn8kon9kyb9m21cofwmx0uu FOREIGN KEY (id_departamento) REFERENCES public.departamentos(id_departamento);


--
-- TOC entry 5046 (class 2606 OID 35682)
-- Name: departamentos fkirtsufa6nwctag8wkfu6b7w1q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT fkirtsufa6nwctag8wkfu6b7w1q FOREIGN KEY (fk_ubicacion) REFERENCES public.ubicaciones(id_ubicacion);


--
-- TOC entry 5045 (class 2606 OID 35672)
-- Name: custodios fkisos3tnkwr9kfdl2vtmthfrmh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custodios
    ADD CONSTRAINT fkisos3tnkwr9kfdl2vtmthfrmh FOREIGN KEY (fk_ubicacion) REFERENCES public.ubicaciones(id_ubicacion);


--
-- TOC entry 5052 (class 2606 OID 35712)
-- Name: imagenes_mantenimiento fkji5hej6vi8eyl18dl690mg6j4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagenes_mantenimiento
    ADD CONSTRAINT fkji5hej6vi8eyl18dl690mg6j4 FOREIGN KEY (id_mantenimiento) REFERENCES public.mantenimientos(id_mantenimiento);


--
-- TOC entry 5062 (class 2606 OID 35752)
-- Name: notificaciones fkjwr4ksj3fmckrotd2v1wk9gk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fkjwr4ksj3fmckrotd2v1wk9gk1 FOREIGN KEY (referencia_mantenimiento_id) REFERENCES public.mantenimientos(id_mantenimiento);


--
-- TOC entry 5032 (class 2606 OID 35612)
-- Name: actividades_realizadas fklxlc368x937yd9l3lrd599rrn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_realizadas
    ADD CONSTRAINT fklxlc368x937yd9l3lrd599rrn FOREIGN KEY (id_actividad) REFERENCES public.actividades_checklist(id_actividad);


--
-- TOC entry 5048 (class 2606 OID 35687)
-- Name: equipos fkn09j9yf2hkj8ijw444mfe49dh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipos
    ADD CONSTRAINT fkn09j9yf2hkj8ijw444mfe49dh FOREIGN KEY (id_categoria) REFERENCES public.categorias_equipo(id_categoria);


--
-- TOC entry 5056 (class 2606 OID 35737)
-- Name: mantenimientos fkn2rgi6eujq76b1v44f7dp289i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos
    ADD CONSTRAINT fkn2rgi6eujq76b1v44f7dp289i FOREIGN KEY (fk_programado) REFERENCES public.mantenimientos_programados(id_programado);


--
-- TOC entry 5049 (class 2606 OID 35697)
-- Name: equipos fkormomovqbwwe9p6dvncq4s6dx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipos
    ADD CONSTRAINT fkormomovqbwwe9p6dvncq4s6dx FOREIGN KEY (fk_ubicacion) REFERENCES public.ubicaciones(id_ubicacion);


--
-- TOC entry 5059 (class 2606 OID 35747)
-- Name: mantenimientos_programados fkqepowqun0q5o9mp1gbqn89irj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos_programados
    ADD CONSTRAINT fkqepowqun0q5o9mp1gbqn89irj FOREIGN KEY (tecnico_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5057 (class 2606 OID 35722)
-- Name: mantenimientos fkrl0h3lf2ephhi4jrplbt528i4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mantenimientos
    ADD CONSTRAINT fkrl0h3lf2ephhi4jrplbt528i4 FOREIGN KEY (empresa_id) REFERENCES public.empresas(id_empresa);


--
-- TOC entry 5033 (class 2606 OID 35617)
-- Name: actividades_realizadas fks6f2omky61vq8ctvk9vydpl9v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_realizadas
    ADD CONSTRAINT fks6f2omky61vq8ctvk9vydpl9v FOREIGN KEY (id_mantenimiento) REFERENCES public.mantenimientos(id_mantenimiento);


--
-- TOC entry 5031 (class 2606 OID 35602)
-- Name: actividades_planificadas fkti6cj08dlgvgn1wwyh56sl8an; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividades_planificadas
    ADD CONSTRAINT fkti6cj08dlgvgn1wwyh56sl8an FOREIGN KEY (fk_mantenimiento_prog) REFERENCES public.mantenimientos_programados(id_programado);


-- Completed on 2026-03-31 09:54:50

--
-- PostgreSQL database dump complete
--

